# Generated by Django 4.0.3 on 2022-05-13 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_subcat2_subcategory_alter_subcat3_subcat2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcat3',
            name='subcat2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.subcat2', verbose_name='Подкатегория 2'),
        ),
        migrations.AlterField(
            model_name='subcat4',
            name='subcat3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.subcat3', verbose_name='Подкатегория 3'),
        ),
    ]
