# Generated by Django 4.0.3 on 2022-03-28 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_products_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
